---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/users/{user_id}/posts":
    get:
      summary: list posts
      tags:
      - Posts
      security:
      - basic_auth: []
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '401':
          description: Unauthorized
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000
